= Limits and throttling

== Limits

To prevent misuse of the REST API and ensure a system's performance and stability, access to the REST API of any given plentysystems system is *throttled*. The following limits apply:

[cols="5"]
|===
|Function |Rate: Basic |Rate: Classic |Rate: Flex |Rate: Plus

|Reading calls per user and minute
|80
|200
|240
|280

|Reading calls per system and day
|59,760
|166,000
|282,000
|282,000

|Writing calls per user and minute
|40
|80
|100
|120

|Writing calls per system and day
|17,280
|48,000
|72,000
|72,000
|===

In addition to these limits, specific routes may be fitted with an individual limit, only applying to this route. For these routes, the limit will be visible in the REST documentation here on the plentymarkets developers website. The route will be labeled with a "THROTTLING" badge, the exact limit can be seen in the "Errors" section of that call.

Bulk REST routes help you to work efficiently within the throttling limits when handling large amounts of data. Check out the xref:rest-api-guides:bulk-routes.adoc[tutorial on bulk routes] to find out which bulk routes are currently available.

== Handling

To give external clients the ability to adjust to these limits and react accordingly, we will send additional headers with each response to a REST call. These headers are prefixed with one of these three prefixes, telling you what specific limitation they are informing about:

[cols="1,3"]
|===
|Header-Prefix |Meaning

|`X-Plenty-Global-Long-Period`
|The information in this header field refers to the *Long period limit*

|`X-Plenty-Global-Short-Period`
|The information in this header field refers to the *Short period limit*

|`X-Plenty-Route`
|The information in this header field refers to the *individual route limit*
|===

Depending on what follows the prefix, the headers have the following meanings:

[cols="1,3"]
|===
|Header |Meaning

|`$PREFIX$-Limit`
|The maximum number of calls for this limit

|`$PREFIX$-Decay`
|Seconds until the current period ends and number of calls gets reset

|`$PREFIX$-Calls-Left`
|Number of calls left for this period
|===

In addition, the following headers will be sent to the client if one or more of these limits are exceeded:

[cols="1,3"]
|===
|Header |Meaning

|`Retry-After`
|Seconds until the current period is over and the call count is reset. Hence, the number of seconds the client must wait until making the next call.

|`$PREFIX$-Calls-Reset`
|Timestamp denoting the point in time when the call count for the specific limit (specified by the prefix) is reset
|===