name: Publish docs update

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
            
      - name: Rebuild site
        uses: peter-evans/repository-dispatch@0e0cf047c08f936c436da4399814cdb4880c8cbf
        with:
          token: ${{ secrets.PUBLIC_PAT_CICD4_PUBLIC }}
          repository: plentymarkets/plenty-developers-docs
          event-type: ContentSourceUpdate
          client-payload: '{ "repository": "${{github.repository}}" }'
